import selectorsCss from './constants.selectorsCss';

// eslint-disable-next-line import/prefer-default-export
export const elementsOfDom = {
    mainClassWrapper: document.querySelector(selectorsCss.classWrapper),
    navHeaderNav: document.querySelector(selectorsCss.classHeaderNav),
    divClassLogo: document.querySelector(selectorsCss.classLogo),
    imgIdThemes: document.querySelector(selectorsCss.idThemes),
    inputIdAuth: document.querySelector(selectorsCss.idAuth),
    sectionclassPopularFilms: document.querySelector(selectorsCss.classPopularFilms),
    allDivClassPopularFilmsItem: document.querySelectorAll(selectorsCss.classPopularFilmsItem),
    allDivClassFilmsPaginationItem:
        document.querySelectorAll(selectorsCss.classFilmsPaginationItem),
    inputIdFilters: document.querySelector(selectorsCss.idFilters),
    sectionClassFiltersItem: document.querySelector(selectorsCss.classFiltersItem),
    buttonIdSaveBtn: document.querySelector(selectorsCss.idSaveBtn),
    buttonIdResetBtn: document.querySelector(selectorsCss.idResetBtn),
    sectionClassFiltersItemNone: document.querySelector(selectorsCss.classFiltersItemNone),
    sectionClassSection: document.querySelector(selectorsCss.classSection),
    inputIdAdult: document.querySelector(selectorsCss.idAdult),
    inputIdInputTitle: document.querySelector(selectorsCss.idInputTitle),
    divIdRevenueMax: document.querySelector(selectorsCss.idRevenueMax),
    divClassContainerInputRange: document.querySelector(selectorsCss.classContainerInputRange),
    divClassContainerSignIn: document.querySelector(selectorsCss.classContainerSignIn),
    divClassContainerSignUP: document.querySelector(selectorsCss.classContainerSignUp),
    buttonIdCheckSignIn: document.querySelector(selectorsCss.idCheckSignIn),
    buttonIdCheckSignUp: document.querySelector(selectorsCss.idCheckSignUp),
    sectionClassPopUp: document.querySelector(selectorsCss.classPopUp),
    buttonIdSetSignUpBtn: document.querySelector(selectorsCss.idSetSignUpBtn),
    buttonIdSetSignInBtn: document.querySelector(selectorsCss.idSetSignInBtn),
    divClassNewFilmsItem: document.querySelector(selectorsCss.classNewFilmsItem),
    templateIdTemplateCard: document.querySelector(selectorsCss.idTemplateCard).content,
    imgClassImgPoster: document.querySelector(selectorsCss.classImgPoster),
    sectionClassNewFilms: document.querySelector(selectorsCss.classNewFilms),
    buttonShowMoreBtn: document.querySelector(selectorsCss.idShowMoreBtn),
    paragraphDescriptionFilm: document.querySelector(selectorsCss.classDescriptionFilm),
    templateFilmsShowMore: document.querySelector(selectorsCss.idFilmsShowMore).content,
    sectionFilmsShowMore: document.querySelector(selectorsCss.classFilmsShowMore),
    divContainerFilmsItem: document.querySelector(selectorsCss.classContainerFilmsItem),
    imgImgFilmsItem: document.querySelector(selectorsCss.classImgFilmsItem),
    buttonIdArrowToUp: document.querySelector(selectorsCss.idArrowToUp),
    divClassContainerFiltersItem: document.querySelector(selectorsCss.classContainerFiltersItem),
    selectIdSelectLanguages: document.querySelector(selectorsCss.idSelectLanguages),
    templateIdLangOptions: document.querySelector(selectorsCss.idLangOptions)
        .content
        .querySelector(selectorsCss.tagOption),
    selectIdSelectGenres: document.querySelector(selectorsCss.idSelectGenres),
    inputIdBudgetMinNumber: document.querySelector(selectorsCss.idBudgetMinNumber),
    inputBudgetMinRange: document.querySelector(selectorsCss.idBudgetMinRange),
    inputIdBudgetMaxNumber: document.querySelector(selectorsCss.idBudgetMaxNumber),
    inputIdBudgetMaxRange: document.querySelector(selectorsCss.idBudgetMaxRange),
    inputIdPopularityMinNumber: document.querySelector(selectorsCss.idPopularityMinNumber),
    inputIdPopularityMinRange: document.querySelector(selectorsCss.idPopularityMinRange),
    inputIdPopularityMaxNumber: document.querySelector(selectorsCss.idPopularityMaxNumber),
    inputIdPopularityMaxRange: document.querySelector(selectorsCss.idPopularityMaxRange),
    inputIdReleaseDayFirst: document.querySelector(selectorsCss.idReleaseDayFirst),
    inputIdReleaseDayLast: document.querySelector(selectorsCss.idReleaseDayLast),
    inputIdRevenueMinNumber: document.querySelector(selectorsCss.idRevenueMinNumber),
    inputIdRevenueMinRange: document.querySelector(selectorsCss.idRevenueMinRange),
    inputIdRevenueMaxNumber: document.querySelector(selectorsCss.idRevenueMaxNumber),
    inputIdRevenueMaxRange: document.querySelector(selectorsCss.idRevenueMaxRange),
    inputIdUsername: document.querySelector(selectorsCss.idUsername),
    inputIdPassword: document.querySelector(selectorsCss.idPassword),
    inputIdFirstName: document.querySelector(selectorsCss.idFirstName),
    inputIdLastName: document.querySelector(selectorsCss.idLastName),
    inputIdSendError: document.querySelector(selectorsCss.idSendError),
    aClassLinkPage: document.querySelector(selectorsCss.classLinkPage),
    inputIdUsernameSignIn: document.querySelector(selectorsCss.idUsernameSignIn),
    inputIdPasswordSignIn: document.querySelector(selectorsCss.idPasswordSignIn),
    divClassContainerBtnReset: document.querySelector(selectorsCss.classContainerBtnReset),
    h1IdHOneDF: document.querySelector(selectorsCss.idHOneDF),
    smallIdErrorLogin: document.querySelector(selectorsCss.idErrorLogin),
    tagSmall: document.querySelector(selectorsCss.tagSmall),
    filmPage: document.querySelector(selectorsCss.filmPage),
    inputClassSearchInput: document.querySelector(selectorsCss.classSearchInput),
    divClassSearch: document.querySelector(selectorsCss.classSearch),
    classErrorHolder: document.querySelector(selectorsCss.classErrorHolder),
    classSignInErr: document.querySelector(selectorsCss.classSignInErr),
};

export const elemsQuerySelectors = {
    filmsItem: elementsOfDom.templateFilmsShowMore.querySelector('.filmsItem'),
    linkPage: elementsOfDom.templateFilmsShowMore.querySelector('.linkPage'),
    imgFilmsItem: elementsOfDom.templateFilmsShowMore.querySelector('.imgFilmsItem'),
    descriptionFilm: elementsOfDom.templateFilmsShowMore.querySelector('.descriptionFilm'),
};
