import { selectorsCss } from "./constants.selectorsCss";

export const elementsOfDom = {
    mainClassWrapper: document.querySelector(selectorsCss.classWrapper),
    navHeaderNav: document.querySelector(selectorsCss.classHeaderNav),
    divClassLogo: document.querySelector(selectorsCss.classLogo),
    imgIdThemes: document.querySelector(selectorsCss.idThemes),
    inputIdAuth: document.querySelector(selectorsCss.idAuth),
    sectionclassPopularFilms: document.querySelector(selectorsCss.classPopularFilms),
    allDivClassPopularFilmsItem: document.querySelectorAll(selectorsCss.classPopularFilmsItem),
    allDivClassFilmsPaginationItem: document.querySelectorAll(selectorsCss.classFilmsPaginationItem),
    inputIdFilters: document.querySelector(selectorsCss.idFilters),
    sectionClassFiltersItem: document.querySelector(selectorsCss.classFiltersItem),
    buttonIdSaveBtn: document.querySelector(selectorsCss.idSaveBtn),
    buttonIdResetBtn: document.querySelector(selectorsCss.idResetBtn),
    sectionClassFiltersItemNone: document.querySelector(selectorsCss.classFiltersItemNone),
    sectionClassSection: document.querySelector(selectorsCss.classSection),
    inputIdAdult: document.querySelector(selectorsCss.idAdult),
    inputIdInputTitle: document.querySelector(selectorsCss.idInputTitle),
    divIdRevenueMax: document.querySelector(selectorsCss.idRevenueMax),
    divClassContainerInputRange: document.querySelector(selectorsCss.classContainerInputRange),
    divClassContainerSignIn: document.querySelector(selectorsCss.classContainerSignIn),
    divClassContainerSignUP: document.querySelector(selectorsCss.classContainerSignUp),
    buttonIdCheckSignIn: document.querySelector(selectorsCss.idCheckSignIn),
    buttonIdCheckSignUp: document.querySelector(selectorsCss.idCheckSignUp),
    sectionClassPopUp: document.querySelector(selectorsCss.classPopUp),
    buttonIdSetSignUpBtn: document.querySelector(selectorsCss.idSetSignUpBtn),
    buttonIdSetSignInBtn: document.querySelector(selectorsCss.idSetSignInBtn),
    divClassNewFilmsItem: document.querySelector(selectorsCss.classNewFilmsItem),
    templateIdTemplateCard: document.querySelector(selectorsCss.idTemplateCard).content,
    imgClassImgPoster: document.querySelector(selectorsCss.classImgPoster),
    sectionClassNewFilms: document.querySelector(selectorsCss.classNewFilms),
    buttonShowMoreBtn: document.querySelector(selectorsCss.idShowMoreBtn),
    paragraphDescriptionFilm: document.querySelector(selectorsCss.classDescriptionFilm),
    templateFilmsShowMore: document.querySelector(selectorsCss.idFilmsShowMore).content,
    sectionFilmsShowMore: document.querySelector(selectorsCss.classFilmsShowMore),
    divContainerFilmsItem: document.querySelector(selectorsCss.classContainerFilmsItem),
    imgImgFilmsItem: document.querySelector(selectorsCss.classImgFilmsItem),
    buttonIdArrowToUp: document.querySelector(selectorsCss.idArrowToUp),
    divClassContainerFiltersItem: document.querySelector(selectorsCss.classContainerFiltersItem),
    selectIdSelectLanguages: document.querySelector(selectorsCss.idSelectLanguages),
    templateIdLangOptions: document.querySelector(selectorsCss.idLangOptions).content.querySelector(selectorsCss.tagOption),
    selectIdSelectGenres: document.querySelector(selectorsCss.idSelectGenres),
    inputIdBudgetMinNumber: document.querySelector(selectorsCss.idBudgetMinNumber),
    inputIdBudgetMaxNumber: document.querySelector(selectorsCss.idBudgetMaxNumber),
    inputIdPopularityMinNumber: document.querySelector(selectorsCss.idPopularityMinNumber),
    inputIdPopularityMaxNumber: document.querySelector(selectorsCss.idPopularityMaxNumber),
    inputIdReleaseDayFirst: document.querySelector(selectorsCss.idReleaseDayFirst),
    inputIdReleaseDayLast: document.querySelector(selectorsCss.idReleaseDayLast),
    inputIdRevenueMinNumber: document.querySelector(selectorsCss.idRevenueMinNumber),
    inputIdRevenueMaxNumber: document.querySelector(selectorsCss.idRevenueMaxNumber)
};

